name: aula-8 actions

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Entrando na pasta
        run: cd aula-7
        
      - name: Instalando o Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalando as dependencias
        run: npm i 

      - name: Realizando os testes
        run: npm test
