name: aula-8 actions

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalando as dependencias
        run: |
          cd aula-7
          npm i 

      - name: Realizando os testes
        run: |
          cd aula-7
          npm test
